### ISSUE TITLE
About IRE and MPS

### ISSUE THREAD

**Issue by King-king424** [bupt-ai-cz/RestNet#7]
Is the IRE module used in all datasets? Or is it only used when target dataset is FSS-1000?
Is MPS only used in training or is it used in both training and inference?

**Comment by King-king424** [comment]
Do you use only one trained model and test it on three target datasets, or do you have a separate trained model for each target dataset to test?
looking forward to your reply，thx.

**Comment by King-king424** [comment]
Is IRE used at training time or inference time?

**Comment by King-king424** [comment]
Can you provide a copy of the inference code and trained weights to ensure that your method can achieve results that are close to those of the paper? If you can, it's a good idea to attach the inference log.
thx.

**Comment by xinyanghuang7** [comment]
Both IRE and MPS are used at all times.
Thank you for your interest, I will consider whether to publish the weights of all data sets after the holidays, but this will be a time-consuming project.
I will definitely upload them if I can and will let you know as soon as possible.
Due to the arrival of CVPR, ECCV and the Lunar New Year as well as the declaration of some additional projects, some work had to be put on hold.
I'm very sorry for delaying your scientific research.
Hope you can understand!

**Comment by xinyanghuang7** [comment]
and i have a separate trained model for each target dataset to test which may be a little different from what you said before.

**Comment by King-king424** [comment]
Thanks for the quick reply. But I still have reservations about the role of the IRE. In my experiments, IRE really made the model perform better on FSS-1000. However, IRE is equivalent to reintroducing domain-related information, which results in poor performance on datasets with large domain shifts such as Chest X-ray and ISIC. And it is difficult to achieve results close to those reported in the paper. And the ablation experiment in your paper was only performed on FSS-1000, and there is no more relevant data.
I look forward to further more complete information from you, which will be of great help to me.
Thanks a lot.
